apiVersion: v1
kind: Service
metadata:
  name: watchtower-metrics
  namespace: watchtower-masterbot
  labels:
    app: watchtower-masterbot
    component: metrics
spec:
  ports:
  - port: 8082
    targetPort: 8082
    protocol: TCP
    name: metrics
  selector:
    app: watchtower-masterbot
