apiVersion: v1
kind: Service
metadata:
  name: watchtower-service
  namespace: watchtower-masterbot
  labels:
    app: watchtower-masterbot
spec:
  selector:
    app: watchtower-masterbot
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
