apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchtower-masterbot
  namespace: watchtower-masterbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchtower-masterbot
  template:
    metadata:
      labels:
        app: watchtower-masterbot
    spec:
      serviceAccountName: watchtower-manager
      containers:
      - name: masterbot
        image: watchtower-masterbot:latest
        imagePullPolicy: Never
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: bot-token
              name: telegram-secrets
        - name: KUBERNETES_NAMESPACE
          value: watchtower-system
