apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: watchtower-masterbot-pdb
  namespace: watchtower-masterbot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: watchtower-masterbot
